development:
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: sberocknroll
  database: mkombat

production:
  adapter: postgresql
  encoding: utf8

test:
  adapter: postgresql
  encoding: utf8
  database: snighter_test
